package common

const ORDER_PLACED = "ORDER_PLACED"
const ORDER_PACKED = "ORDER_PACKED"

const DELIVERY_STARTED = "DELIVERY_STARTED"
const DELIVERY_COMPLETE = "DELIVERY_COMPLETE"

const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"

func GetAllSubjects() []string {
	return []string{
		ORDER_PLACED,
		DELIVERY_STARTED,
		ORDER_PACKED,
		DELIVERY_COMPLETE,
		PAYMENT_SUCCESS,
	}
}
